package awesomechatapp;


public enum Operation {
        CREATE_USER, TRY_LOGIN, VERIFY_CODE, LOGOUT, CHECK_FRIEND_REQUESTS, 
        FRIENDSHIP_CONFIRMED, FRIENDSHIP_IGNORED, GET_FRIENDS_INFO, GET_USER_AVATAR, 
        SAVE_USER_AVATAR, MAKE_RECEIVER_SOCKET, FORGOT_PASSWORD, RESET_PASSWORD
}
